### ISSUE TITLE
Feature Request: Derive Enum types

### ISSUE THREAD

**Issue by cgbur** [TedDriggs/field_names#1]
It would be useful if you could also have a similar derive for getting the enum types. 

Currently, when parsing a string to match an enum my error messages are handwritten. Could be dynamically generated.

**Comment by TedDriggs** [comment]
I've added `VARIANTS` as an associated const in the linked PR. Please give it a look and confirm it'll meet your use-case here.

**Comment by cgbur** [comment]
```rust
use field_names::VariantNames;

#[derive(VariantNames)]
enum Colors {
  Red,
  Orange,
  BrightGreen,
}

println!("{:?}", Colors::VARIANTS);
```
```bash
["Red", "Orange", "BrightGreen"]
```

Works perfectly! Excited to start using this in projects.

**Comment by TedDriggs** [comment]
(Reopening so it's closed by the merge to master)
